# src/main/resources/application.yml

server:
  port: 8080 # ??????????? 8080

spring:
  datasource:
    # ???1????????
    # ? YOUR_ALIYUN_IP 47.120.31.133
    # ? YOUR_DB_NAME ???? DBeaver ???????? (?? course_db)
    # serverTimezone=Asia/Shanghai ????????8??
    url: jdbc:mysql://47.120.31.133:3306/camp_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    
    # ????
    username: root
    password: password123 # ??
    
    # ???? (MySQL 8.0+ ???)
    driver-class-name: com.mysql.cj.jdbc.Driver
